### ISSUE TITLE
Expose underlying compression libraries directly

### ISSUE THREAD

**Issue by mrocklin** [Blosc/python-blosc#101]
Sometimes I want to use some parts of blosc but not others.  In particular I use blosc to gain access to other compression libraries (like snappy) but don't want the added features of blocked parallel compression (I handle parallelism on my own.)  What are your thoughts on exposing some of the internal building blocks out to the Python layer?

I would love functions like `blosc.shuffle`, `blosc.lzo.compress`, `blosc.snappy.compress`, etc..  I would use `blosc` in several more applications if these were available to me directly.  It would be especially useful if these did not hold on to the GIL.

**Comment by FrancescAlted** [comment]
I think what you are after is `blosc_compress_ctx` and `blosc_decompress_ctx`:

https://github.com/Blosc/c-blosc/blob/master/blosc/blosc.h#L184
https://github.com/Blosc/c-blosc/blob/master/blosc/blosc.h#L222

Using these with `numinternalthreads=1` will allow you to use them from multithreaded apps without locks.  Also, you can select different compressors like blosclz, lz4, lz4hc, snappy and zlib, and if you want to get rid of the internal blocking you can do that by using `blocksize=nbytes`.

Although these `_ctx` functions are not wrapped yet in python-blosc, they would be a nice addition and we would welcome a PR indeed.

**Comment by esc** [comment]
Two things about the functions you are suggesting.

`blosc.lzo.compress` doesn't make sense right now, since we don't handle lzo.
`blosc.shuffle` I am not sure if this even makes sense with larger blocksizes

Also, there must be bindings for the compressors you want. Would it make sense to use those directly? Or are you looking for a uniform interface to them?

**Comment by mrocklin** [comment]
I'm looking for a uniform interface to the relevant options maintained by people that I trust care that it was done well.

**Comment by jcrist** [comment]
> Although these _ctx functions are not wrapped yet in python-blosc, they would be a nice addition and we would welcome a PR indeed.

From the comment [here](https://github.com/Blosc/c-blosc/blob/master/blosc/blosc.h#L107), it sounds like `init` can't be called if you want to use the context functions? If this is the case, then some workaround would be needed to avoid calling `init` in `blosc.__init__` on import.

**Comment by esc** [comment]
@jcrist that sounds right.

**Comment by esc** [comment]
@mrocklin I am assuming it is O.K. to close this since Dask now has compression support.
