### ISSUE TITLE
Memory leak in blosc.decompress in current master

### ISSUE THREAD

**Issue by sdvillal** [Blosc/python-blosc#102]
If I run this, I get quickly into memory troubles:

```python
import psutil
x = 'aj lkajfldkfjaoiur 0983 5t93h308 ajlkf n fsfhahtey8 haiuoyajkah ' * 100000
counter = 0
freemem = psutil.avail_phymem() / 1024. ** 3
while freemem > 1:
    cx = blosc.compress(x, typesize=1, clevel=1, shuffle=False, cname='blosclz')
    blosc.decompress(cx)
    freemem = psutil.avail_phymem() / 1024. ** 3
    counter += 1
    if counter % 10000 == 0:
        print('%.2f GB' % freemem)

# 10.56 GB
# 8.66 GB
# 6.75 GB
# 4.84 GB
# 2.91 GB
# 1.01 GB
```
But if I run this, I don't:

```python
import psutil
x = 'aj lkajfldkfjaoiur 0983 5t93h308 ajlkf n fsfhahtey8 haiuoyajkah ' * 100000
cx = blosc.compress(x, typesize=1, clevel=1, shuffle=False, cname='blosclz')
counter = 0
freemem = psutil.avail_phymem() / 1024. ** 3
while freemem > 1:
    blosc.decompress(cx)
    freemem = psutil.avail_phymem() / 1024. ** 3
    counter += 1
    if counter % 10000 == 0:
        print('%.2f GB' % freemem)

# 12.44 GB
# 12.44 GB
# 12.44 GB
# ...
```

That makes me think that decompress is not freeing memory used by the compressed data. And that the bug has been introduced in some recent commit to python-blosc.

I get the leak with python-blosc from master, spiced with c-blosc 1.7.0 (although I think the particular version of c-blosc is not relevant here).  If I run python-blosc 1.2.7 and c-blosc 1.7.0, everything works like a charm - winning combination, because if I use older versions of lz4hc I get segfaults, the reason why I got into all this trouble at first instance.

**Comment by esc** [comment]
You could use ``git bisect`` to try to locate the commit that introduced the bug.

**Comment by sdvillal** [comment]
That was fun. Bisect blames 23852161a5abe6.

**Comment by sdvillal** [comment]
I guess we just need to release the view buffer. Will give it a try and open a PR if it works.

**Comment by esc** [comment]
You can also look at the zlib module from the standard library to see how it is done there. I used that as inspiration.
