### ISSUE TITLE
Error when building 1.2.7 on python 3.5.1 (Anaconda 2.5, Windows)

### ISSUE THREAD

**Issue by thequackdaddy** [Blosc/python-blosc#109]
Hello, 

See this for more info: https://github.com/Blosc/bloscpack/issues/46

@esc Suggested I post a bug here instead... 

I have Anaconda 2.5 (Python 3.5.1) with Visual Studio community edition. I can compile and install 1.2.8 (or 1.2.9dev0 from github) with no problems. With 1.2.7, pip install blosc==1.2.7 gives me all this nastiness....

Both 1.2.8 and 1.2.9dev0 seem to build just fine. (I'm using these while playing with castra).

uild\temp.win-amd64-3.5\Release\c-blosc/internal-complibs\zlib-1.2.8\inflate.obj
 build\temp.win-amd64-3.5\Release\c-blosc/internal-complibs\zlib-1.2.8\inftrees.
obj build\temp.win-amd64-3.5\Release\c-blosc/internal-complibs\zlib-1.2.8\trees.
obj build\temp.win-amd64-3.5\Release\c-blosc/internal-complibs\zlib-1.2.8\uncomp
r.obj build\temp.win-amd64-3.5\Release\c-blosc/internal-complibs\zlib-1.2.8\zuti
l.obj /OUT:build\lib.win-amd64-3.5\blosc\blosc_extension.cp35-win_amd64.pyd /IMP
LIB:build\temp.win-amd64-3.5\Release\blosc\blosc_extension.cp35-win_amd64.lib
    blosc_extension.obj : warning LNK4197: export 'PyInit_blosc_extension' speci
fied multiple times; using first specification
       Creating library build\temp.win-amd64-3.5\Release\blosc\blosc_extension.c
p35-win_amd64.lib and object build\temp.win-amd64-3.5\Release\blosc\blosc_extens
ion.cp35-win_amd64.exp
    shuffle.obj : error LNK2001: unresolved external symbol blosc_get_cpu_featur
es
    build\lib.win-amd64-3.5\blosc\blosc_extension.cp35-win_amd64.pyd : fatal err
or LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\amd64\\link.exe' failed with exit status 1120

    ----------------------------------------
Command "C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:
\\Users\\PQUACK~1\\AppData\\Local\\Temp\\pip-build-7u774njl\\blosc\\setup.py';ex
ec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'
), __file__, 'exec'))" install --record C:\Users\QUACK~1\AppData\Local\Temp\pip
-rbdprlu1-record\install-record.txt --single-version-externally-managed --compil
e" failed with error code 1 in C:\Users\QUACK~1\AppData\Local\Temp\pip-build-7u
774njl\blosc\

[Anaconda3] C:\Users\pquackenbush\git>

**Comment by FrancescAlted** [comment]
Hi.  I have just released python-blosc 1.3.0 which comes with C-Blosc 1.8.0.  The later should be able to compile just fine on Windows.  Can you have a try at it?

**Comment by thequackdaddy** [comment]
It probably will... the problem is that bloscpack requires [1.2.7](https://github.com/Blosc/bloscpack/blob/master/setup.py#L14). 

Indeed, 1.2.8 and 1.2.9 both compile. But if 1.2.7 can't compile, you can't get bloscpack.

**Comment by esc** [comment]
With 0.11 bloscpack is now up-to-date with current python-blosc, all should be well, closing.
