### ISSUE TITLE
v1.4.3 gives `error: Error -1 while decompressing data`

### ISSUE THREAD

**Issue by solarix888** [Blosc/python-blosc#115]
specifically in `blosc.toplevel`,  `decompress_ptr()` returns with error.  This is called from Pandas v.0.18.1  `pd.read_msgpack()`

**Comment by FrancescAlted** [comment]
Hmm, I have tested decompress_ptr() [quite extensively](https://github.com/Blosc/python-blosc#benchmarking) before releasing 1.4.3.  Could you please post a minimal example reproducing the problem?

**Comment by jreback** [comment]
@FrancescAlted we just received the same issue on our builds: https://github.com/pydata/pandas/issues/14143

this works on macosx, failing on linux though.

**Comment by jreback** [comment]
@FrancescAlted ahh I see @solarix888 reported this from pandas ok, let me see if i can repro

**Comment by jreback** [comment]
hmm, I cannot repro this locally (on a 64-bit linux vm). maybe some conflict with some other libs on linux?

**Comment by solarix888** [comment]
Hmm, my specific use case is that I save a pandas DataFrame to msgpack using the pd.to_msgpack() method, compressed using blosc. Then I read it back later. In this case, the compressed DataFrame was compressed with the previous version python-blosc, and then version update, I wasn't able to decompress.

**Comment by jreback** [comment]
```
-> return _ext.decompress(bytesobj, as_bytearray)
(Pdb) l
480         ...                                      as_bytearray=True)) is bytearray
481         True
482  
483         """
484  
485  ->     return _ext.decompress(bytesobj, as_bytearray)
486  
487  
488     def decompress_ptr(bytesobj, address):
489         """decompress_ptr(bytesobj, address)
490  
(Pdb) p bytesobj
'\x02\x01\x01\x08\xf0\x00\x00\x00\xf0\x00\x00\x00L\x00\x00\x00\x14\x00\x00\x004\x00\x00\x00!\x00\x00\xe0\xaa\x00\x1f\xf0\x00\x08\x10\x14\x18\x1c "$&(*,.0123456789:;<=\x00?@\xe0\t\x00\x08@@@@@@@@@'
```

so this appears to be a compress-decompress ONLY on 2.7/linux. In this example we are using latin-1 encoding (but not sure if that matters)

The data is coming from a file that we created 
[here](https://github.com/pydata/pandas/blob/master/pandas/io/tests/data/legacy_msgpack/0.17.1/0.17.1_x86_64_linux_2.7.11.msgpack). 

I don't know the exact version of blosc that was used originally, maybe https://github.com/kawochen remembers (this was checked in 7 months ago)

And working on 1.4.1 just fine.


lmk if any other data can provide

**Comment by FrancescAlted** [comment]
Yep, I can reproduce that.  There is a fix in: https://github.com/Blosc/c-blosc/commit/07d4bb0989fe54bcf75135b5b457a10ff5547bee.  I'll try to release new versions of C-Blosc and Python-Blosc as soon as possible,

**Comment by FrancescAlted** [comment]
I have released new versions of C-Blosc (1.11.1) and Python-Blosc (1.4.4).  Please give them a test.

**Comment by jreback** [comment]
thanks @FrancescAlted looks great!

**Comment by eapetitfils** [comment]
I had a very similar issue with version **1.5.1**, getting an exit code -1073741819 while decompressing data generated with pandas msgpack function.

Upgrading to blosc **1.6.1** on the environment doing the decompression fixed the issue. The compression is still performed with blosc 1.5.1.
