### ISSUE TITLE
Maintain conda packages on conda forge

### ISSUE THREAD

**Issue by mrocklin** [Blosc/python-blosc#118]
Many people in the community have switched to building packages automatically on [conda-forge](https://conda-forge.github.io/).  The [getting started](https://conda-forge.github.io/#add_recipe) procedure is relatively straightforward if you already have a conda recipe.  

Having up-to-date conda packages in a community maintained channel would make it easier for downstream libraries (like Dask) to rely on Blosc more heavily.

This would be a nice task for anyone who wants to help out Blosc and get involved in community package management.  A deep knowledge of the blosc codebase is not necessary.

**Comment by esc** [comment]
can this be done automatically from travis?

**Comment by mrocklin** [comment]
Conda-forge uses travis-ci for Mac builds, circle-ci for linux builds, and AppVeyor for Windows builds.  

The maintenance required is to bump a version number whenever you release.  Here is an example maintenance PR: https://github.com/conda-forge/dask-feedstock/pull/7

Separately the conda-forge team will update recipes automatically as issues arise.

**Comment by FrancescElies** [comment]
Maybe this could help as a starting point https://github.com/conda-forge/staged-recipes/commit/e650915a23ab4dd22e168d3a4e1ce2018e1e0441

**Comment by FrancescElies** [comment]
I opened a PR https://github.com/conda-forge/staged-recipes/pull/1869

**Comment by mrocklin** [comment]
Thanks for starting this @FrancescElies .  I'm happy to see momentum here :)

**Comment by FrancescElies** [comment]
I was just informed there is already a feedstock https://github.com/conda-forge/python-blosc-feedstock, with an older version though

**Comment by mrocklin** [comment]
Tests are failing on that version.  Looks like it could use some help.

**Comment by FrancescElies** [comment]
https://github.com/conda-forge/python-blosc-feedstock/pull/2

**Comment by jakirkham** [comment]
Thanks for stepping up @FrancescElies .

We do try to notify upstream when we package something at conda-forge. However, it seems we may have missed reaching out in this case. Sorry about that.

If you have any thoughts or questions about the process, please don't hesitate to raise them. It's always nice to get an outsider's perspective. 😄

**Comment by FrancescAlted** [comment]
I don't exactly know the status for this.  Can we close it?  Also, we need to do something for triggering the build of forthcoming python-blosc 1.5.1?

**Comment by FrancescElies** [comment]
We need to update the version on the feedstock https://github.com/conda-forge/python-blosc-feedstock/pull/5

**Comment by esc** [comment]
@mrocklin is this still desired?

**Comment by mrocklin** [comment]
It looks like @FrancescElies has made the feedstock.  https://github.com/conda-forge/python-blosc-feedstock and python-blosc seems to be available on conda-forge.

The last update was a bit over a year ago, although maybe that's the last update of python-blosc as well?  Regardless, this should probably be closed.

**Comment by FrancescElies** [comment]
That's right the feedstock is at the moment three versions behind.
There are at the moment two open prs:
- https://github.com/conda-forge/python-blosc-feedstock/pull/11 (v1.6.1)
- https://github.com/conda-forge/python-blosc-feedstock/pull/7 (v1.5.1)
Yesterday I pushed a tiny fix for pr v1.5.1 but it still fails, some builds froze during tests and others had a failing test due to empty string decompression error (I believe this was the regression mentioned in another issue)
