### ISSUE TITLE
Check License

### ISSUE THREAD

**Issue by FrancescElies** [Blosc/python-blosc#121]
In the python blosc feedstock says the package is apache 2, Is this license correct?
https://github.com/conda-forge/python-blosc-feedstock/blob/master/recipe/meta.yaml#L32-L35

**Comment by FrancescAlted** [comment]
Yes, although in the last months I was reconsidering using a BSD license instead, basically for the reasons outlined in [this discussion](http://softwareengineering.stackexchange.com/questions/41128/what-is-the-purpose-of-the-non-endorsement-clause-in-the-new-bsd-license?noredirect=1&lq=1).  In fact, the change has been done already for [C-Blosc](https://github.com/Blosc/c-blosc/commit/d026b1de8ba6953ec2564d4f4ee3f1e328a82d0d), and I'd like to propagate it to other projects under the Blosc umbrella (unless somebody objects).

**Comment by FrancescElies** [comment]
shall I close this one?

**Comment by FrancescAlted** [comment]
License has been updated to BSD in 3810bac.  Closing.

**Comment by esc** [comment]
I am re-opening this issue, because it was never actually fixed in the feedstock.

https://github.com/conda-forge/python-blosc-feedstock/blob/master/recipe/meta.yaml#L42

**Comment by esc** [comment]
This actually propagates through and pages like the following don't actually show accurate licensing details:

https://anaconda.org/conda-forge/python-blosc

**Comment by esc** [comment]
I have started fixing theis:

https://github.com/conda-forge/python-blosc-feedstock/pull/19

**Comment by esc** [comment]
v1.8.1 hit the conda-forge channel on anaconda.org - the license information propagated accordingly and this issue is now fixed.
