### ISSUE TITLE
support aarch64?

### ISSUE THREAD

**Issue by itdaniher** [Blosc/python-blosc#123]
`pip install blosc` on aarch64 / python3.5.2 errors out due to cpuinfo.py not having a match clause for aarch64.

This is solvable by adding the following three lines:

```
+       elif re.match('^aarch64$', raw_arch_string):
+               arch = 'AARCH_64'
+               bits = 64
```

Cheers!
Ian

**Comment by FrancescAlted** [comment]
Done!
