### ISSUE TITLE
Need `lizard` branch

### ISSUE THREAD

**Issue by robbmcleod** [Blosc/python-blosc#128]
I would like to submit a pull request to support the `c-blosc` candidate branch `lizard`  in `python-blosc` found here:

https://github.com/robbmcleod/python-blosc/tree/lizard

but I need a corresponding branch to pull against.

**Comment by FrancescAlted** [comment]
The Lizard codec is still subjected to a request for feedback from the Blosc community.  Do you have any arguments in favor of this one?

**Comment by robbmcleod** [comment]
I sent benchmarks off to a student, hopefully he will be able to get the library installed now and return some tests for Xeon v.3 CPUs. My initial tests with Lizard and just SSE2 weren't compelling.  It was in-between 'lz4' and 'zstd' in time but only very marginally better than 'lz4' in compression ratio. Our data is very difficult to compress, however.

If you don't have interest in a Lizard branch would you like a PR on the master's `setup.py` so the codecs are separated from blosc using `build_clib.py` and you don't have namespace collision again in the future?

**Comment by FrancescAlted** [comment]
Well, I am not sure I fully understand your proposal, but send your PR against master and let's discuss there.

**Comment by robbmcleod** [comment]
Closing FTM based on #129.
