### ISSUE TITLE
Corrupted data when using bitshuffle?

### ISSUE THREAD

**Issue by will133** [Blosc/python-blosc#133]
Perhaps I don't quite understand the typesize parameter, but would doing the following be incorrect when using blosc.compress?

I'm running this on Mac with Python 3.6.2 using the default python-blosc package from conda-forge.  Here it seems like the decompress does not give me back the original string value:

```
$ python
Python 3.6.2 | packaged by conda-forge | (default, Jul 23 2017, 23:01:38)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> x = numpy.ones(27266, dtype='uint8')
>>> xx = x.tobytes()
>>> import blosc
>>> blosc.decompress(blosc.compress(xx, clevel=5, cname='zstd', shuffle=blosc.BITSHUFFLE))[-3:]
b'\x01  '
>>> blosc.decompress(blosc.compress(xx, clevel=5, cname='zstd', shuffle=blosc.SHUFFLE))[-3:]
b'\x01\x01\x01'
>>> blosc.decompress(blosc.compress(xx, clevel=5, cname='zstd'))[-3:]
b'\x01\x01\x01'
```

As you can see, with the bitshuffle filter, the values from the decompress seems corrupted at the very end (with two \x00 instead of \x01).  Do you have any idea why?

Here is my environment.yml:

```
name: test_blosc
channels:
- conda-forge
- defaults
dependencies:
- blas=1.1=openblas
- blosc=1.12.0=0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- libgfortran=3.0.0=0
- ncurses=5.9=10
- numpy=1.13.3=py36_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pip=9.0.1=py36_0
- python=3.6.2=0
- python-blosc=1.4.4=py36_0
- readline=6.2=0
- setuptools=36.6.0=py36_1
- snappy=1.1.7=1
- sqlite=3.13.0=1
- tk=8.5.19=2
- wheel=0.30.0=py_1
- xz=5.2.3=0
- zlib=1.2.11=0
prefix: /Users/wlee/miniconda3/envs/test_blosc
```

**Comment by will133** [comment]
I try this example with typesize=1, and it seems to work:

```
>>> blosc.decompress(blosc.compress(xx, typesize=1, clevel=5, cname='zstd', shuffle=blosc.BITSHUFFLE))[-3:]
b'\x01\x01\x01'
```

Am I required to always set the typesize so  len(buffer) % typesize == 0?  Does it seem somewhat dangerous when you can end up with corrupted data if you forget to set the typesize?

**Comment by FrancescAlted** [comment]
Yep.  The bitshuffle filter is a bit finicky on the buffer sizes.  That was a bug in C-Blosc, so I fixed it in the copy here (but still needs to be propagated upstream).

**Comment by esc** [comment]
`master` on travis-ci is still broken, should we re-open?

**Comment by FrancescAlted** [comment]
Yeah, what is failing is the new test introduced in https://github.com/Blosc/python-blosc/commit/a1d1f6f5548753dfa001f9ac1ac17a1c0d3af244.  The problem is that I cannot not reproduce it on neither my Linux or my Mac box :/ . Any help trying to reproduce this would be welcome!
