### ISSUE TITLE
Is it possible to remove the MAX_BUFFERSIZE restriction?

### ISSUE THREAD

**Issue by dhirschfeld** [Blosc/python-blosc#134]
I just run into this issue:
```python-traceback
C:\Miniconda3\lib\site-packages\blosc\toplevel.py in compress(bytesobj, typesize, clevel, shuffle, cname)
    359     """
    360 
--> 361     _check_input_length('bytesobj', len(bytesobj))
    362     _check_typesize(typesize)
    363     _check_shuffle(shuffle)

C:\Miniconda3\lib\site-packages\blosc\toplevel.py in _check_input_length(input_name, input_len)
    299     if input_len > blosc.MAX_BUFFERSIZE:
    300         raise ValueError("%s cannot be larger than %d bytes" %
--> 301                          (input_name, blosc.MAX_BUFFERSIZE))
    302 
    303 

ValueError: bytesobj cannot be larger than 2147483631 bytes
```

...so it looks like you're currently restricted to `sizeof(int32)` or ~2GB. Is there any way around this restriction?

**Comment by FrancescAlted** [comment]
Yes, that limitation comes from the fact that upstream C-Blosc library has the same limitation.  The plan is to get rid of this in C-Blosc2 (that should propagate to python-blosc2 shortly after).

**Comment by janosh** [comment]
The limitation appears to still be in place.

```py
blosc.__version__
'1.10.6'
```

Is it safe/any good to do `blosc.MAX_BUFFERSIZE = 2 ** 32`?

**Comment by dumblob** [comment]
I have the same question about increasing MAX_BUFFERSIZE as @janosh . Anyone?

**Comment by FrancescAlted** [comment]
Unfortunately this is not possible inside python-blosc 1.x series.  But C-Blosc 2.x series (aka [C-Blosc2](https://github.com/Blosc/c-blosc2/blob/main/README.rst)) has introduced support for super-chunks, with support for up to 2**63 bytes.  C-Blosc2 is in production state, and we are building a [python wrapper around it](https://github.com/Blosc/python-blosc2/blob/main/README.rst).  Here it is an [usage example](https://github.com/Blosc/python-blosc2/blob/main/examples/schunk.py).  Hope this helps!

**Comment by dumblob** [comment]
Ok, then the only thing is to wait for `python-blosc2`. Thanks anyway!
