### ISSUE TITLE
Cannot Install Python Blosc or Bcolz on Windows

### ISSUE THREAD

**Issue by ghost** [Blosc/python-blosc#138]
I have been trying for 2 days and cannot install python blosc or bcolz. C-Blosc installs okay (about 160 warnings though), but I get this error with python blosc:

blosc/blosc_extension.c(633): error C2065: 'BLOSC_MAX_THREADS': undeclared identifier
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2.

Please help! Let me know if you need more information.

**Comment by FrancescAlted** [comment]
Hmm, the BLOSC_MAX_THREADS symbol was introduced long ago, so something really weird seems to be happening.  Would you provide more detail on the specific steps that you are following?

**Comment by ahendry2688** [comment]
Yes of course. So, I decided to start over.  I installed C-Blosc library no problem, but when I try to install python-blosc and get to `python setup.py build_ext --inplace --blosc="C:\Program Files (x86)\blosc"` I get this:

    running build_ext
    building 'blosc.blosc_extension' extension
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL 
    /DNDEBUG /MD "-IC:\Program Files (x86)\blosc\include" -IC:\Users\adam.hendry\AppData\Local\Programs\Python\Python35\include -IC:\Users\adam.hendry\AppData\Local\Programs\Python\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /Tcblosc/blosc_extension.c /Fobuild\temp.win-amd64-3.5\Release\blosc/blosc_extension.obj
    blosc_extension.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files (x86)\blosc\lib" /LIBPATH:C:\Users\adam.hendry\AppData\Local\Programs\Python\Python35\libs /LIBPATH:C:\Users\adam.hendry\AppData\Local\Programs\Python\Python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" blosc.lib /EXPORT:PyInit_blosc_extension build\temp.win-amd64-3.5\Release\blosc/blosc_extension.obj /OUT:build\lib.win-amd64-3.5\blosc\blosc_extension.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\blosc\blosc_extension.cp35-win_amd64.lib
    blosc_extension.obj : warning LNK4197: export 'PyInit_blosc_extension' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.5\Release\blosc\blosc_extension.cp35-win_amd64.lib and 
    object build\temp.win-amd64-3.5\Release\blosc\blosc_extension.cp35-win_amd64.exp
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_cbuffer_sizes
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_free_resources
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_cbuffer_complib    
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_destroy
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_get_complib_info
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_compress
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_set_nthreads
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_init
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_get_blocksize
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_compname_to_compcode
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_compress_ctx
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_set_blocksize
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_set_compressor
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_decompress_ctx
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_get_nthreads
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_compcode_to_compname
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_decompress
    blosc_extension.obj : error LNK2001: unresolved external symbol blosc_list_compressors
    build\lib.win-amd64-3.5\blosc\blosc_extension.cp35-win_amd64.pyd : fatal error LNK1120: 18 
    unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' 
    failed with exit status 1120

**Comment by ahendry2688** [comment]
Could there by chance be something wrong with the linking order?

**Comment by esc** [comment]
@ahendry2688 did you get anywhere with this in the meantime?

**Comment by esc** [comment]
We released a new version, you could try that perhaps?

**Comment by esc** [comment]
The reporting user account no longer exists on github. Closing this.
