### ISSUE TITLE
numpy specified as requirement only for testing.

### ISSUE THREAD

**Issue by cosmin-lazar-zahacinschi** [Blosc/python-blosc#158]
https://github.com/Blosc/python-blosc/blob/bad3b2e116269499187f3f5c726ad43707f3da03/setup.py#L39

This is not very consistent and breaks builds for users that only require blosc.

**Comment by esc** [comment]
O. K. can you open an issue in the issue tracker? 

On 22 October 2018 09:25:31 CEST, cosmin-lazar-zahacinschi <notifications@github.com> wrote:
>https://github.com/Blosc/python-blosc/blob/bad3b2e116269499187f3f5c726ad43707f3da03/setup.py#L39
>
>This is not very consistent and breaks builds for users that only
>require blosc.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Blosc/python-blosc/issues/158

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by esc** [comment]
I also see that `numpy` is a top-level dependency in master right now:

https://github.com/Blosc/python-blosc/blob/master/blosc/toplevel.py#L11

Would it suffice to simply remove that line? @cosmin-lazar-zahacinschi

**Comment by esc** [comment]
In any case, I have made a branch that tries to do away entirely with the `numpy` dependency but I am stuck at skipping doctests, any help would be appreciated.

#159

**Comment by esc** [comment]
Yeah, the big question is, should numpy be a strict requirement or optional. Until 1.6.1 it has been optional and I would like to make it like that again, because making it a strict requirement breaks backwards compatability and doesn:t respect the existing interface. This means moving the numpy import in toplevel.py (back) to inside the numpy related functions.  I don't think that either #160 or #159 are good solutions.

**Comment by esc** [comment]
I just released 1.6.2, which should fix this issue. If not, please re-open.

**Comment by agates** [comment]
@esc 1.6.2 works for me.  It lets me remove numpy as a hard dependency in an application that uses blosc :).  Thank you!

**Comment by esc** [comment]
@agates thanks for the feedback, happy it works for you now.
