### ISSUE TITLE
installation on power9

### ISSUE THREAD

**Issue by jstrube** [Blosc/python-blosc#162]
I am installing blosc on power9. Unfortunately, the cpuinfo.py that is shipped here is too old.
Simply removing the shipped file and installing the latest version via pip: `pip install py-cpuinfo` seems to solve the problem.

**Comment by esc** [comment]
Do you think it will suffice to upgrade the vendored version?

**Comment by jstrube** [comment]
I think that would work, but wouldn't it be easier to just add this as a dependency rather than shipping it?

**Comment by esc** [comment]
In principle, yes, however the cpuinfo is used in the setup.py. This means it is needed before dependencies can be installed, effectively a catch-22 problem.

**Comment by jstrube** [comment]
I see. Fine with me.
Thanks for the explanation.

**Comment by jstrube** [comment]
That seems to work. Thank you.

**Comment by esc** [comment]
@jstrube thanks for circling back to confirm this, your help is appreciated. You can expect this fix to be contained within the next release of python-blosc.
