### ISSUE TITLE
failing test on empty byte array

### ISSUE THREAD

**Issue by beckermr** [Blosc/python-blosc#171]
I seem to be getting a failing test when installing on mac osx. 

Here is MWE

```bash
$ python -c 'import blosc; print(b"" == blosc.decompress(blosc.compress(b"", 1)))'
Output buffer size should be larger than 16 bytes
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.6/site-packages/blosc-1.6.3.dev0-py3.6-macosx-10.9-x86_64.egg/blosc/toplevel.py", line 423, in compress
    return _ext.compress(bytesobj, typesize, clevel, shuffle, cname)
blosc_extension.error: Error -1 while compressing data
```

I installed blosc without linking to the conda c-blosc libraries.

**Comment by beckermr** [comment]
Also the numpy downgrade is super weird, but that is a conda issue.

**Comment by esc** [comment]
Hi @beckermr thank you very much for reporting this. Unfortunately I don't know (or forgot) how the conda-forge package is built or who maintains it. It would be helpful if you could dig up some more details about this.

**Comment by beckermr** [comment]
The bug shows up without conda forge as well so I don’t think that is the cause.

**Comment by esc** [comment]
There was a bug in c-blosc 1.14.4 which was unable to compress an empty buffer, it might be related to that. Note however, that c-blosc 1.14.4 was never vendored with python-blosc making this an unlikely target. Can you give details on how you installed python-blosc and what version you used?

**Comment by beckermr** [comment]
Aaaaarg! I reinstalled and now it works from both pip and master. Sorry for the trouble! :(

Let's close this issue for now and I will reopen if I see this again.

**Comment by esc** [comment]
@beckermr no worries! Thanks for taking the time to engage. If you hit any other snags please don't hesitate to get in touch.
