### ISSUE TITLE
New `cpuinfo` misses `AVX2` flag on Windows

### ISSUE THREAD

**Issue by robbmcleod** [Blosc/python-blosc#173]
This issue:

https://github.com/workhorsy/py-cpuinfo/issues/108

causes `blosc` to build without AVX2 support on Windows. A test script:

    import cpuinfo
    info = cpuinfo.get_cpu_info()
    print('----')
    print(info['flags'])

generates the output twice due to multiprocessing calls:

    ----
    ['3dnow', 'acpi', 'clflush', 'cmov', 'de', 'dts', 'fxsr', 'ia64', 'mca', 'mce', 'mmx', 'msr', 'mtrr', 'pse', 'sep', 'serial', 'ss', 'sse', 'sse2', 'tm', 'tsc'] ----
    ['3dnow', '3dnowprefetch', 'abm', 'acpi', 'adx', 'aes', 'apic', 'avx', 'avx2', 'avx512bw', 'avx512cd', 'avx512dq', 'avx512f', 'avx512vl', 'bmi1', 'bmi2', 'clflush', 'clflushopt', 'clwb', 'cmov', 'cx16', 'cx8', 'dca', 'de', 'ds_cpl', 'dtes64', 'dts', 'erms', 'est', 'f16c', 'fma', 'fpu', 'fxsr', 'hle', 'ht', 'ia64', 'intel_pt', 'invpcid', 'lahf_lm', 'mca', 'mce', 'mmx', 'monitor', 'movbe', 'mpx', 'msr', 'mtrr', 'osxsave', 'pae', 'pat', 'pbe', 'pcid', 'pclmulqdq', 'pdcm', 'pge', 'pni', 'popcnt', 'pqe', 'pqm', 'pse', 'pse36', 'rdrnd', 'rdseed', 'rtm', 'sep', 'serial', 'smap', 'smep', 'ss', 'sse', 'sse2', 'sse4_1', 'sse4_2', 'ssse3', 'tm', 'tm2', 'tsc', 'tscdeadline', 'vme', 'vmx', 'x2apic', 'xsave', 'xtpr']

In `setup.py` it gets the first, incomplete, set of CPU flags, and the other set overwrites the variable later, in a nice race condition. 

Ugly work-around is to call `cpuinfo.get_cpu_info()` at the top of the file, so it has time to overwrite the dictionary. Or put in a call to `time.sleep()`.

Edit: actually putting the call at the top of the file causes the `setup()` function to be called twice (ugh) even if I protect it with `__name__ == '__main__'`.

    > python setup.py install
    False
    SSE2 detected
    True
    SSE2 detected
    AVX2 detected
    running install
    running bdist_egg
    running egg_info 

Perhaps reverting to `cpuinfo <= 3.3.0` would be best.

**Comment by esc** [comment]
This looks really ugly, maybe we should wait for cpuinfo to fix it on their side?
