### ISSUE TITLE
AVX2 CPU detection fails to build on old GCC versions

### ISSUE THREAD

**Issue by ndevenish** [Blosc/python-blosc#193]
We're running RHEL, which comes with gcc (GCC) 4.4.7, but on newer CPU machines.

The AVX2 capability is picked up, but GCC doesn't have the capability to use it, so `python setup.py build` (or via pip) fails with:
```
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_LZ4=1 -DHAVE_ZLIB=1 -DHAVE_ZSTD=1 -Ic-blosc/blosc -Ic-blosc/internal-complibs/lz4-1.8.3 -Ic-blosc/internal-complibs/snappy-1.1.1 -Ic-blosc/internal-complibs/zlib-1.2.8 -Ic-blosc/internal-complibs/zstd-1.3.8 -Ic-blosc/internal-complibs/lz4-1.8.3 -Ic-blosc/internal-complibs/zstd-1.3.8/common -Ic-blosc/internal-complibs/zstd-1.3.8 -I/...../modules/python-2.7.15/include/python2.7 -c blosc/blosc_extension.c -o build/temp.linux-x86_64-2.7/blosc/blosc_extension.o -DSHUFFLE_SSE2_ENABLED -msse2 -DSHUFFLE_AVX2_ENABLED -mavx2
cc1: error: unrecognized command line option "-mavx2"
```

I can bypass this locally with `DISABLE_BLOSC_AVX2` but obviously that can't be encoded into a normal package management requirements list. Would it be possible to e.g. check the minimum gcc version before passing these flags?

**Comment by esc** [comment]
@ndvenish thanks for reporting this! Please feel free to submit a pull-request to fix this!

**Comment by Anthchirp** [comment]
this may be useful/instructive:
https://stackoverflow.com/questions/28641408/how-to-tell-which-compiler-will-be-invoked-for-a-python-c-extension-in-setuptool
