### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by esc** [Blosc/python-blosc#201]
Is it time?

**Comment by FrancescAlted** [comment]
It would be nice to first update and release c-blosc with latest versions of codecs (mainly LZ4, Zstd and BloscLZ).

**Comment by esc** [comment]
:+1:

**Comment by esc** [comment]
I just reviewed the release procedure, it should be trivial to crank out a new release as soon as c-blosc is updated. Looking forward to it!

**Comment by FrancescAlted** [comment]
1.8.2 is out, so closing.
