### ISSUE TITLE
AMD zen compilation issue

### ISSUE THREAD

**Issue by phineas0fog** [Blosc/python-blosc#203]
EDIT: I have the same issue on an Intel CPU

gcc version: 9.1.0
cmake version: 3.15.0

EDIT2: `DISABLE_BLOSC_AVX2=1 pip install blosc` seems work

Hi :)

I tried to install the lib on my dev workstation and it fails.

I tried this:
- install with `pip install blosc`: fail
- clone the repo then `python setup.py install`: fail
- clone the repo then use the cmake commands to build the `c-blosc` sources: success

The error is: `c-blosc/blosc/shuffle.c:177:1: error: conflicting types for ‘_xgetbv’`.

I am not very good with C and low-level programming but I noticed that XGETBV is directly related to the CPU and all my coworkers have installed the lib without any issue. But I am the only one using an AMD Ryzen CPU (2700x). So I tried on another machine with a Ryzen too (1600x) and it fails too but ok on an Intel CPU.

Thanks for your help :heart:

**Comment by phineas0fog** [comment]
EDIT: solved with `DISABLE_BLOSC_AVX2=1 pip install blosc` solve the issue but weird anyway.

**Comment by FrancescAlted** [comment]
Yes, although the C-Blosc library has proper detection of XGETBV, python-blosc machinery is more flaky in this regard, so if you want a portable binary you need to explictly disable AVX2 during compilation (as you did).

**Comment by FrancescAlted** [comment]
FWIW, Zen supports AVX2 since the beginning, so not sure why your box has problems with AVX2 in binaries. https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#AVX2

**Comment by bm371613** [comment]
It's possible to get it to work without disabling AVX2 by using an older version of gcc, like `CC=gcc-8 pip install blosc`.

**Comment by FrancescAlted** [comment]
Should be fixed in recent 1.8.2 release.
