### ISSUE TITLE
loading packed array in python 2.6 in python 3.0 error

### ISSUE THREAD

**Issue by yaoli** [Blosc/python-blosc#205]
When calling `blosc.unpack_array(t)` in python 3, I had `*** TypeError: only string (2.x) or bytes (3.x) objects supported as input`. `t` is saved in python 2 by calling `blosc.pack_array()`. 

Is there a way to bypass this issue?

As a side note, I've tried `blosc.unpack_array(t.encode('utf-8'))`, but it gives this error `*** blosc_extension.error: Error 61361913 : not a Blosc buffer or header info is corrupted`. 

Thank you!

**Comment by yaoli** [comment]
As a side note, I've tried `blosc.unpack_array(t.encode('utf-8'))`, but it gives this error `*** blosc_extension.error: Error 61361913 : not a Blosc buffer or header info is corrupted`.

**Comment by yaoli** [comment]
ok, found a solution! `blosc.unpack_array(t.encode('latin1'), encoding='latin1')`

**Comment by Valaybundele** [comment]
Hi @yaoli,
I am getting this error `TypeError: only string (2.x) or bytes (3.x) objects supported as input` when i am trying to unpack images using blosc.unpack_array() in python 3.6. I also tried using `blosc.unpack_array(t.encode('latin1'), encoding='latin1')` but its giving the error `blosc_extension.error: Error 61361913 : not a Blosc buffer or header info is corrupted`. Anything else which I should try?
Thanks
