### ISSUE TITLE
1.8.1 from pypi won't build

### ISSUE THREAD

**Issue by clham** [Blosc/python-blosc#209]
I'm getting the following error when trying to build anything after 1.5.1.
`c-blosc/blosc/shuffle.c:170:1: error: conflicting types for ‘_xgetbv’`
I'm using GCC-9.2.1. I've tried the various `DISABLE_BLOSC_*` flags listed in the docs. Please let me know what further info I can provide.

**Comment by ptrstn** [comment]
Same for me. I'm using Manjaro Linux and ```gcc``` version 9.2.0

The installation works if I install the package using the GitHub URL.

```bash
pip install git+https://github.com/Blosc/python-blosc/
```

**Comment by FrancescAlted** [comment]
Thanks for the heads-up.  As @ptrstn suggests, using master should fix this and provided that a new release of C-Blosc has been recently made, a new version should be done soon.

**Comment by FrancescAlted** [comment]
Should be fixed in recent 1.8.2 release.
