### ISSUE TITLE
Failed to build blosc

### ISSUE THREAD

**Issue by PREM1980** [Blosc/python-blosc#211]
I'm using this package and while building, get the following error - 

Building wheels for collected packages: blosc
  Building wheel for blosc (PEP 517): started
  Building wheel for blosc (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpnfdwbr3n
       cwd: /tmp/pip-install-jlvlkum_/blosc
  Complete output (84 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 8.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is unknown
  CMake Error at CMakeLists.txt:4 (ENABLE_LANGUAGE):
    No CMAKE_CXX_COMPILER could be found.
  
    Tell CMake where to find the compiler by setting either the environment
    variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    to the compiler, or to the compiler name if it is in the PATH.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-jlvlkum_/blosc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-jlvlkum_/blosc/_cmake_test_compile/build/CMakeFiles/CMakeError.log".
  Not searching for unused variables given on the command line.
  CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-jlvlkum_/blosc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  
  

 Trying "Ninja" generator
 Trying "Ninja" generator - failure

Trying "Unix Makefiles" generator
Trying "Unix Makefiles" generator - failure

  
  ********************************************************************************
  scikit-build could not get a working generator for your system. Aborting build.
  
  Building Linux wheels for Python 3.7 requires a compiler (e.g gcc).
  It can be installed using debian package manager:
  
    sudo apt-get install build-essential
  
  To build compliant wheels, consider using the manylinux system described in PEP-513.
  Get it with "dockcross/manylinux-x64" docker image:
  
    https://github.com/dockcross/dockcross#readme
  
  For more details, please refer to scikit-build documentation:
  
    http://scikit-build.readthedocs.io/en/latest/generators.html#linux
  
  ********************************************************************************
  ----------------------------------------
  ERROR: Failed building wheel for blosc
  Running setup.py clean for blosc
Failed to build blosc

**Comment by FrancescAlted** [comment]
Judging by this error "No CMAKE_CXX_COMPILER could be found.", I'd say that you need to install a C++ compiler.  Technically C-Blosc does not need a C++ compiler if one does not want the snappy codec (which is disabled by default), but detecting one is the default in cmake.  I'll open a ticket for this.

**Comment by FrancescAlted** [comment]
Overridden by https://github.com/Blosc/c-blosc/issues/284
