### ISSUE TITLE
BLOSC_DIR environment variable seems defunct as of v1.8.3

### ISSUE THREAD

**Issue by mbargull** [Blosc/python-blosc#216]
The `BLOSC_DIR` build environment variable does not seem to be used anywhere.
A search on the repository only shows https://github.com/Blosc/python-blosc/search?q=BLOSC_DIR&unscoped_q=BLOSC_DIR :
- https://github.com/Blosc/python-blosc/blob/v1.8.3/doc/install.rst#compiling-with-an-installed-blosc-library
- https://github.com/Blosc/python-blosc/blob/v1.8.3/README.rst#compiling-with-an-installed-blosc-library
- https://github.com/Blosc/python-blosc/blob/v1.8.3/setup.py#L97

The `install.rst` and `README.rst` also have to be amended to remove the `--blosc=/usr/local` option.

**Comment by aginiewicz** [comment]
Is there some other way to build using system-wide blosc library?

**Comment by FrancescAlted** [comment]
@aginiewicz that's a good question.  I think the `BLOSC_DIR` support was invalidated after the support for `scikit-build` compilation method.  There was an [attempt to support it again](https://github.com/Blosc/python-blosc/commit/f9ec31fee1fb99b85e17da798d6622a6f4f9f898), but this was not the correct way for fixing the problem.  Maybe @thewtex can suggest a way for fixing this one?

At any rate, this should be either fixed or remove the documentation about it, as @mbargull suggested.

**Comment by thewtex** [comment]
To best support using a different version of c-blosc in python-blosc and to support using c-blosc in other C/C++ project, a [cmake package configuration file](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html) should be created by c-blosc, then the path to the directory with this file can be passed with a `Blosc_DIR` can argument to scikit-build via

```
python setup.py build -- -DBlosc_DIR=/path/to/c-blosc-build
```

This enabled c-blosc to provide its build configuration, an client projects to use it. It is easier to use (everything is provided by the single Blosc_DIR), and it is much more reliable and strongly encouraged over requiring cmake to guess locations and built settings, which brittle.
