### ISSUE TITLE
Compressed array with pack_array smaller than with compress?

### ISSUE THREAD

**Issue by tazr** [Blosc/python-blosc#221]
I have a 2D `float64` array that I compress using either `compress` or `pack_array`:

      res1 = blosc.pack_array(im) # len 354022
      res2 = blosc.compress(im.tostring(), typesize=8) # len 354484

What surprises me is that the length of the compressed result is smaller with `pack_array`. In my understanding, the compression should be the same in both cases, with the former adding some metadata on top of it -- therefore I would expect it to be slightly larger.

The difference is insignificant in practice (around 0.1% difference in length) but I still found this behavior intriguing, especially since this situation happens frequently in my case: more than 60% of my images compress better with `pack_array`). I checked that the images are stored contiguously in case it could come from a different read order.

Is it because the default settings are chosen differently in `pack_array` than in `compress`? If not what could it be?

**Comment by robbmcleod** [comment]
Is  your itemsize actually 8? I.e. what's the result of the following:

   res2 = blosc.compress(im.tobytes(), typesize=im.dtype.itemsize)

**Comment by tazr** [comment]
Yes, it really is -- my image is in `float64` as I stated in my OP. Actually I tried with different values of `typesize` and the compression ratio gets significantly worse when not the actual type size, so I would rule out a different choice for this parameter by `pack_array` and `compress` in this case.

**Comment by FrancescAlted** [comment]
Yeah, in my experience, these differences of < 1% are common in compressing different datasets, and I would not pay too much attention to it.

**Comment by tazr** [comment]
Oh, is it because the meta-data is compressed along with the data? Somehow I was assuming it was added on top. In that case it makes sense.
