### ISSUE TITLE
blosc 1.8.3 installing to purelib directory not platlib

### ISSUE THREAD

**Issue by toddrme2178** [Blosc/python-blosc#222]
I am trying to package python-blosc for openSUSE Linux and I am running into an issue where the package is installing to the architecture-independent `purelib` directory rather than the architecture-specific `platlib` directory.  This is incorrect, since it contains compiled C code.  Specifically, it is being installed into:

```
/usr/lib/python3.7/site-packages/blosc
```

Instead of

```
/usr/lib64/python3.7/site-packages/blosc
```

This didn't happen in 1.8.1, so it seems to be something new with the switch to scikit-build.

**Comment by FrancescAlted** [comment]
Yes, using scikit-build is probably the reason why this is happening.  @thewtex do you have some suggestion here?

**Comment by thewtex** [comment]
@toddrme2178 what command is used to install the package?

@jcfr

**Comment by bnavigator** [comment]
@thewtex see here:
https://build.opensuse.org/package/view_file/devel:languages:python:numeric/python-blosc/python-blosc.spec?expand=1
```
%python_exec setup.py install -O1 --skip-build --force --root %{buildroot} --install-purelib=%{$python_sitearch}
```

I guess the `--install-purelib` parameter is a hack to override the install into `$python_sitelib`

**Comment by toddrme2178** [comment]
@thewtex The command I used that didn't work was:

```
python3 setup.py build_ext --inplace
python3 setup.py build
python3 setup.py install -O1 --skip-build --force --root=%{buildroot} --prefix=%{_prefix}
```

The version @bvnavigator showed above is indeed a hack to workaround this issue by forcing the purelib package to be installed in platlib.

**Comment by thewtex** [comment]
@toddrme2178 @bnavigator the next place to look is

https://github.com/scikit-build/scikit-build/blob/0c33f15b0c0452e8bd70ab6057b4d283d6025b51/skbuild/command/install.py#L20-L23

if it is possible to debug the state and path taken there.

**Comment by FrancescAlted** [comment]
Is this a problem anymore?
