### ISSUE TITLE
Depreaction warning due to invalid escape sequences in Python 3.7

### ISSUE THREAD

**Issue by tirkarthi** [Blosc/python-blosc#225]
Depreaction warning due to invalid escape sequences in Python 3.7 . https://github.com/asottile/pyupgrade/ can be used to resolve the warnings.

```
find . -iname '*py' | grep -Ev 'setup|rdf4' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./cpuinfo.py:553: DeprecationWarning: invalid escape sequence \d
  if re.match('^i\d86$|^x86$|^x86_32$|^i86pc$|^ia32$|^ia-32$|^bepc$', raw_arch_string):
```

**Comment by DimitriPapadopoulos** [comment]
Note that `cpuinfo.py` is a vendored file, as far as I know the original file is maintained in project https://github.com/workhorsy/py-cpuinfo. You might want to open an issue directly in that project  instead.

**Comment by FrancescAlted** [comment]
cpuinfo.py is not vendored anymore.  Closing.

**Comment by DimitriPapadopoulos** [comment]
Additionally, I believe the invalid escapes have been fixed in https://github.com/workhorsy/py-cpuinfo/commit/dc477fcd4d70386f67cb711e371d2d79cdc6c27c.
