### ISSUE TITLE
`setup.py build` fails on ppc64

### ISSUE THREAD

**Issue by mgorny** [Blosc/python-blosc#227]
When trying to build python-blosc-1.9.1 on ppc64, `setup.py` fails due to missing `flags` key on `cpu_info`:

```
python3.7 setup.py build -j 12
Traceback (most recent call last):
  File "setup.py", line 90, in <module>
    '-DDEACTIVATE_SSE2:BOOL=%s' % cmake_bool(('DISABLE_BLOSC_SSE2' in os.environ) or (cpu_info is None) or ('sse2' not in cpu_info['flags'])),
KeyError: 'flags'
```

Original bug report: https://bugs.gentoo.org/732178

**Comment by FrancescAlted** [comment]
Thanks for bringing this to our attention.  My guess is that the `cpuinfo` module needs to be updated somehow.
