### ISSUE TITLE
“python_requires” should be set with “>=3.6”, as blosc 1.10.6 is not compatible with all Python versions.

### ISSUE THREAD

**Issue by PyVCEchecker** [Blosc/python-blosc#268]
Currently, the keyword argument **python_requires** of **setup()** is not set, and thus it is assumed that this distribution is compatible with all Python versions. 
However, I found the following code checking Python compatibility locally in **setup.py**
```python
    if sys.version_info[0] == 3:
        if sys.version_info[1] < 6:
            exit_with_error("You need Python 3.6 or greater to install blosc!")
    else:
        exit_with_error("You need Python 3.6 or greater to install blosc!")
```
I think it is a better way to declare Python compatibility by using the keyword argument **python_requires** than checking compatibility locally for some reasons:
* Descriptions in **python_requires** will be reflected in the metadata
* “pip install” can check such metadata on the fly during distribution selection, and prevent from downloading and installing the incompatible package versions. 
* If the user does not specify any version constraint, pip can automatically choose the latest compatible package version for users.

Way to improve:
modify **setup()** in **setup.py,** add **python_requires** keyword argument:
```python
setup(…
     python_requires=">=3.6",
     …)
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by DimitriPapadopoulos** [comment]
Additionally, the module is documented to support Python 3.7 to 3.9:
https://github.com/Blosc/python-blosc/blob/7d40da5f6183ee136988628f7da49f721307a281/setup.py#L66-L69

**Comment by PyVCEchecker** [comment]
But I think it is a better way to declare Python compatibility by using the keyword argument **python_requires** than argument **classifiers** or checking compatibility locally for some reasons:
* Descriptions in **python_requires** will be reflected in the metadata
* “pip install” can check such metadata on the fly during distribution selection , and prevent from downloading and installing the incompatible package versions. （**classifiers** don't work on pip）
* If the user does not specify any version constraint, pip can automatically choose the latest compatible package version for users.
