### ISSUE TITLE
LICENSES/BLOSC.txt

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/python-blosc#274]
Any reason why there's a **`LICENSES/BLOSC.txt`** file in addition to **`LICENSE.txt`**?

**Comment by FrancescAlted** [comment]
Yep.  The former refers to the C library.  But it is true that it would be better to rename this as **`LICENSES/C-BLOSC.txt`**.

**Comment by DimitriPapadopoulos** [comment]
Indeed it is unclear which software package `LICENSES/C-BLOSC.txt` applies to because there is no mention of the software package inside the file - `LICENSES/C-BLOSC.txt` and `LICENSE.txt` are identical.

**Comment by DimitriPapadopoulos** [comment]
But then there's already a **`blosc/c-blosc/LICENSES/BLOSC.txt`** file. Do you really need **`LICENSES/BLOSC.txt`**?

Additionally, these two files are inconsistent:
```diff
$ diff LICENSES/BLOSC.txt blosc/c-blosc/LICENSES/BLOSC.txt
6c6
< Copyright (C) 2019-Present The Blosc Development Team
---
> Copyright (C) 2019-present Blosc Development team <blosc@blosc.org>
```
