### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/python-blosc#285]
The default branch has been renamed to `main` in [c-blosc](https://github.com/Blosc/c-blosc/branches), [c-blosc2](https://github.com/Blosc/c-blosc2/branches), [python-blosc2](https://github.com/Blosc/python-blosc2/branches). It would be great if you could rename it in this repository too, for consistency.

**Comment by FrancescAlted** [comment]
Done.
