### ISSUE TITLE
Update pypi with latest blosc version

### ISSUE THREAD

**Issue by mroeschke** [Blosc/python-blosc#297]
It appears that the latest version on conda-forge is `1.21.1`: https://anaconda.org/conda-forge/blosc

It appears that the latest version on pypi is `1.10.6`: https://pypi.org/project/blosc/#history

It would be great if pypi could be updated with the latest blosc version; otherwise, is pypi still supported?

**Comment by FrancescAlted** [comment]
I think there is a misunderstanding here. 1.21.1 is the version of the [C-Blosc](https://github.com/Blosc/c-blosc) library (in conda-forge they are using the somewhat confusing `blosc` name for that).  And 1.10.6 is the (latest) version of the [Python-Blosc](https://github.com/Blosc/python-blosc) package and it *does exist* in PyPI.

At any rate, there is the relatively new [Python-Blosc2](https://github.com/Blosc/python-blosc2) package that exposes a very similar API (just a bit more modernized, like e.g. using Enums for codecs and filters, and other bells and whistles) than `Python-Blosc`.  Also, its conda-forge name, `python-blosc2`, is way more appropriate.

**Comment by mroeschke** [comment]
Ah I didnt know there was a difference between the C and Python library (including library)

Also not sure if I'm missing something, but I don't see `python-blosc2` on conda-forge: https://anaconda.org/search?q=python-blosc2


```
% mamba install -c conda-forge python-blosc2


                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.24.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['python-blosc2']

pkgs/main/osx-64                                            Using cache
pkgs/main/noarch                                            Using cache
pkgs/r/osx-64                                               Using cache
pkgs/r/noarch                                               Using cache
conda-forge/noarch                                  10.0MB @   4.3MB/s  2.6s
conda-forge/osx-64                                  24.2MB @   4.7MB/s  5.9s

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - nothing provides requested python-blosc2
```

**Comment by mroeschke** [comment]
Just to clarify my motivation: I am trying to resolve `blosc` as an optional dependency in pandas and how to install on pip & conda

So for `blosc` it would be?

Pypi: `pip install blosc` (latest version 1.10.6)
Conda: `conda install -c conda-forge python-blosc`  (latest version 1.10.6)


And for `blosc2` it would be
Pypi: `pip install blosc2` (latest version 0.5.2)
Conda: ?
