### ISSUE TITLE
Wheel for Python 3.10 and Python 3.11

### ISSUE THREAD

**Issue by JPirralha-Sensei** [Blosc/python-blosc#310]
Hello,

I'd like to use python-blosc with Python 3.10 and 3.11. I see that support has already been added to the source, when are updated wheels expected to be published?

Thank you.

**Comment by FrancescAlted** [comment]
Hi.  Yes, we are aware of that, and waiting for some free cycles for doing this.  Meanwhile you might be interested in trying python-blosc2 which come with wheels for Python 3.10 and 3.11.  python-blosc2 has recently received a couple of small development grants and this is where action is actively happening.

**Comment by JPirralha-Sensei** [comment]
Thank you.

It is for an existing project. At some point we will migrate to python-blosc2.

**Comment by FrancescAlted** [comment]
Python 3.10 and 3.11 wheels are avilable for the latest release.
