### ISSUE TITLE
README link to python-blosc2 seems useful

### ISSUE THREAD

**Issue by nmstoker** [Blosc/python-blosc#321]
This looks like a great project!

After investigating for a while I realised there's actually a python -blosc2 which is largely a drop in replacement for python -blosc:

https://github.com/Blosc/python-blosc2

To help new people get started with the latest version, it seems like it might be worth linking to python-blosc2 in an obvious unmissable way, right near the top of the README.

**Comment by FrancescAlted** [comment]
Good idea.  Added in f5fbd63.
