### ISSUE TITLE
__pack_tensor__ must be made portable and not depend on Python

### ISSUE THREAD

**Issue by dmikushin** [Blosc/python-blosc#322]
Hi @lbolla, @FrancescAlted and everyone!

Blosc2 is the data communication language of the future! Overall, Blosc2 is very portable, but I've recently stumbled upon one questionable aspect.

Blosc2 communicates tensor shapes using `__pack_tensor__` variable-length metadata token. To my surprise, this token content is a **Python object** serialized with msgpack. This means that even if I want to use Blosc2 data frames in a purely C++ application, I need to bring up the whole Python interpreter to read the content of `__pack_tensor__`.

In fact, `__pack_tensor__` should not require Python. It's a string for kind, then an array of integers for shape, and again a string for data type. I believe all of these can be expressed in plain data without involving Python, which would allow Blosc2 to be truly portable.

It's just a historical matter that python-blosc and PyTables are the first two practical applications of Blosc. Therefore, they standardize in their own way some aspects that should rather be a part of the abstract core design. I mean, `__pack_tensor__` should be a part of c-blosc2, and my question should rather apply there; c-blosc2 should define a universal form of `__pack_tensor__`, which all higher-level applications should conform to.

Does this make sense, or do I miss any counter arguments?

**Comment by FrancescAlted** [comment]
`__pack_tensor__` is a bit of adding more metadata (whether the saved tensor is PyTorch, TensorFlow or NumPy instance) on top of the existing [b2nd metalayer](https://github.com/Blosc/c-blosc2/blob/main/README_B2ND_METALAYER.rst).  The latter is completely based on msgpack and meant to be portable among different languages (not only Python), and IMO, this is the one to be used for communicating NDim datasets in general.

**Comment by dmikushin** [comment]
Hi @FrancescAlted , so you mean __pack_tensor__ is portable as long as msgpack is portable. For example, there is a purely C++ implementation of msgpack: https://github.com/msgpack/msgpack-c . OK, makes sense, thank you!
