### ISSUE TITLE
support memoryviews even on bytearray?

### ISSUE THREAD

**Issue by ThomasWaldmann** [Blosc/python-blosc#78]
Seems like attic (which is py3 only) would want to give a memoryview on a bytearray (called data) to blosc's compress, but it doesn't get accepted there, so I would have to use bytes(data) to first convert to an acceptable type - and this would make a full new copy of it, right?

I tried to losen the first type check in blosc to accept memoryviews also, but then it just fails a little later with:

```
    return _ext.compress(bytesobj, typesize, clevel, shuffle, cname)
TypeError: must be read-only pinned buffer, not memoryview
```

Seems like code like that (see HAS_NEW_BUFFER) might be useful (but please check, I am not familiar with low-level stuff):

https://github.com/dlitz/pycrypto/pull/81/files#diff-d29a5dec14d8ca1fc5d169320636fc52R631

**Comment by esc** [comment]
I ran into this too, see #65

**Comment by esc** [comment]
Thanks for the research, check #80 for a potential solution.

**Comment by esc** [comment]
@ThomasWaldmann  #80 was merged to master I'd really appreciate if you could check it out.

**Comment by esc** [comment]
There is now also #94 for decompressing from a memoryview or bytearray.

**Comment by FrancescAlted** [comment]
@ThomasWaldmann Could you check if the newest release fixes this issue?

**Comment by esc** [comment]
ping! I'll close this under the vague assumption that it has been fixed. Feel free to open a new ticket if this is a mistake.
