### ISSUE TITLE
numpy dependency not honoured in setup.py

### ISSUE THREAD

**Issue by esc** [Blosc/python-blosc#84]
Isn't being installed automatically or checked for.

**Comment by FrancescAlted** [comment]
I don't think numpy should be a hard dependency, right?

**Comment by esc** [comment]
No, but the tests fail if it isn't installed, perhaps the best behaviour would be to check if it is there and skip the tests, if it is not?

**Comment by esc** [comment]
Not all tests, just those that require it.

**Comment by esc** [comment]
The problem are the doctests, there doesn't seem to be any way to conditionally exclude them
