### ISSUE TITLE
Support for recognizing AVX2 instructions

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/python-blosc#95]
In order to detect AVX2 instructions and activate it, it may be a good idea to use:

https://github.com/FlightDataServices/PyCPUID

so as to detect if AVX2 flags can be used to compile c-blosc directly from setuptools.

The only 'problem' that I can see is that PyCPUID has a LGPL which can somewhat collide with BSD that is used for distribution purposes.

**Comment by FrancescAlted** [comment]
Another approach is to split the `blosc_get_cpu_features()` function (see https://github.com/Blosc/c-blosc/blob/master/blosc/shuffle.c#L59) on its own source file that can be compiled independently prior to compile c-blosc itself.  A bit more work, but we wouldn't need to add the PyCUID dependency.

**Comment by esc** [comment]
These all sound like terribly hacky ideas...

**Comment by FrancescAlted** [comment]
The `cpuinfo.py` module takes care of this, so closing.
