### ISSUE TITLE
Release GIL

### ISSUE THREAD

**Issue by mrocklin** [Blosc/python-blosc#99]
I would like to use single-threaded `blosc.compress/decompress` in many threads in parallel.  My understanding is that this is possible in the C layer by creating many contexts but not currently possible in the Python layer.

**Comment by FrancescAlted** [comment]
This would be possible by wrapping the `blosc_compress_ctx` and `blosc_decompress_ctx` functions.  See #101 for details.

**Comment by mrocklin** [comment]
Is this resolved by #116 ?

**Comment by esc** [comment]
It would appear so.

**Comment by esc** [comment]
Does closing this warrant a new release?
